[theme] # You have to add this line

# Primary accent for interactive elements
primaryColor="#94381F"

# Background color for the main content area
# backgroundColor = '#273346'
backgroundColor="#002b36"


# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#B9F1C0'
secondaryBackgroundColor="#586e75"


# Color used for almost all text
# textColor = '#FFFFFF'
textColor="#fafafa"


# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
